name: tests

on: 
    push:
        branches:
            - master

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1','8.2','8.3']
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"
        
      - name: Install php ${{ matrix.php }} dev 
        run: |
          sudo apt install libopenblas-dev
          sudo apt install liblapacke-dev
          sudo apt install php${{ matrix.php }}-dev

      - name: Download rindow-matlib
        run: |
          ( cd .. && git clone https://github.com/rindow/rindow-matlib )
          ( cd ../rindow-matlib && git checkout 1.0.0 )
          ( cd ../rindow-matlib && cmake -S . -B build )

      - name: Build
        run: |
          composer update
          phpize${{ matrix.php }}
          ./configure --enable-rindow_openblas --with-rindow_matlib=../rindow-matlib --with-php-config=php-config${{ matrix.php }}
          make clean
          make

      - name: Install rindow_openblas
        run: |
          sh ./packaging.sh ${{ matrix.php }}
          ls *.deb
          sudo apt install -y ./rindow-openblas-php${{ matrix.php }}_0.4.0-1+ubuntuXX.XX_amd64.deb

      - name: Install phpunit
        run: |
          composer require phpunit/phpunit=8.5.*

      - name: Tests
        run: |
          phpunit -c phpunit


